site_name: Indian Village Boundaries (Maps)
site_description: A project website for Indian village boundary maps in geojson format for download and reuse. 
theme_dir: cinder
copyright: "Indian Village Boundaries (Maps)  is licensed under the <a href='https://github.com/datameet/indian_village_boundaries/blob/master/LICENSE.md'>ODbl license</a>"
pages:
    - Home: index.md
    - Contributing: contributing.md
    - Reference: reference.md
    - Tools: tools.md
    - Tutorials: tutorials.md
    - States:
        - Bihar: br.md
        - Karnataka: ka.md
        - Kerala: kl.md
        - Goa: ga.md
        - Gujarat: gj.md
site_dir: './../docs'
extra_css:
    - css/extra.css